#pragma once

using namespace ATL;

template <class T>
class CProxy_IAutomationTesterEvents : public IConnectionPointImpl<T, &__uuidof(_IAutomationTesterEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
